---
name: Source Log
description: This issue template is intended to record information about a data source, its graph(s), workflow(s), its current status, and any pending tasks.

body:
  - type: input
    id: webpage
    attributes:
      label: Web Page URL
      description: "Enter the URL of the web page where the source data is available"
      placeholder: "https://example.com/whats-on/"
  - type: textarea
    id: graph-workflow
    attributes:
      label: Graph(s) and GitHub Workflow(s)
      description: "Provide links to the data source's graph(s) and GitHub workflow(s). Leave this table empty if no workflow has been created yet. 
      Here are quick links to help you retrieve commonly used GitHub repositories:
      https://github.com/culturecreates/artsdata-orion |  
      https://github.com/culturecreates/artsdata-planet-spektrix | 
      https://github.com/culturecreates/artsdata-planet-footlight |   
      https://github.com/artsdata-stewards/artsdata-orion"
      value: |
        | Graph | Workflow |
        | ----------------- | ----------------- |
        | EnterFullURI | Link |
        | EnterFullURI | Link |
  - type: dropdown
    id: status
    attributes:
      label: Status
      options: 
        - Need help with entity identifier
        - Awaiting data quality check
        - Waiting for the provider to make changes to their data
        - Need auto-minting from Culture Creates
        - Need graph rankings
        - Not sure
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Provide any other relevant information. For example, if this website is meant to replace an older source, provide the name of the graph that should be deleted."
---
