---
name: Source Log
description: This issue template is intended to record information about a data source, its graph(s), workflow(s), its current status, and any pending tasks.

body:
  - type: input
    id: name
    attributes:
      label: Maintainer Name
      description: "Enter the name of the organization responsible for maintaining this data source."
  - type: input
    id: webpage
    attributes:
      label: Web Page URL
      description: "Enter the URL of a web page where the data source is available."
      placeholder: "https://example.com/whats-on/"
  - type: textarea
    id: graph-workflow
    attributes:
      label: Graph(s) and GitHub Workflow(s)
      description: "Provide links to the data source's graph(s) and GitHub workflow(s), along with each graph's auto-minting status. Leave this table empty if no workflow has been created yet. 
      Here are quick links to help you retrieve commonly used GitHub repositories:
      https://github.com/culturecreates/artsdata-orion |  
      https://github.com/culturecreates/artsdata-planet-spektrix | 
      https://github.com/culturecreates/artsdata-planet-footlight |   
      https://github.com/artsdata-stewards/artsdata-orion"
      value: |
        | Graph | Workflow | Automint |
        | ----------- | ----------- | ----------- |
        | EnterFullURI | Link | TRUE |
        | EnterFullURI | Link | FALSE |
  - type: dropdown
    id: status
    attributes:
      label: Status
      options: 
        - Need help with entity identifier
        - Awaiting data quality check
        - Waiting for the provider to make changes to their data
        - Need auto-minting from Culture Creates
        - Need graph rankings
        - Not sure
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: "Here is a list of sample tasks associated with loading a new sources. Edit this list as you see fit."
      value: |
        - [ ] ...
        - [ ] Set up GitHub workflow
        - [ ] Turn auto-minting on
        - [ ] Assign ranking
        - [ ] Notify the data provider
        - [ ] ...
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: "Provide any other relevant information. For example, if this website is meant to replace an older source, provide the name of the graph that should be deleted."
---
